---
ID: "74b07569-b5fe-4c4a-b678-214958f9c1df"
Parent: "a116a928-af13-4269-bc04-f24225b58efd"
Template: "a116a928-af13-4269-bc04-f24225b58efd"
Path: /sitecore/templates/Feature/Espire Accelerator/Espire Components/Article Banner Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {2E81F2EE-5E1E-48C6-BDDC-EA49DEEE290E}
    {A116A928-AF13-4269-BC04-F24225B58EFD}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2e7f0302-f072-491b-a514-2613fd754feb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240103T130835Z
